### ISSUE TITLE
Debug tree missing header files

### ISSUE THREAD

**Issue by campej** [vapor/vapor#2538]
vapor build
Building project...
warning: dependency 'fluent' is not used by any target
warning: dependency 'fluent-sqlite-driver' is not used by any target
warning: dependency 'leaf' is not used by any target
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/configure.swift:2:8: error: could not build Objective-C module 'FluentSQLiteDriver'
import FluentSQLiteDriver
       ^
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/configure.swift:2:8: error: could not build Objective-C module 'FluentSQLiteDriver'
import FluentSQLiteDriver
       ^
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/configure.swift:2:8: error: could not build Objective-C module 'FluentSQLiteDriver'
import FluentSQLiteDriver
       ^
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/configure.swift:2:8: error: could not build Objective-C module 'FluentSQLiteDriver'
import FluentSQLiteDriver
       ^
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/FluentSQLiteDriver.build/FluentSQLiteDriver-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/configure.swift:2:8: error: could not build Objective-C module 'FluentSQLiteDriver'
import FluentSQLiteDriver
       ^

Fatal error: result 1: file VaporToolbox/exec.swift, line 55
Illegal instruction: 4
### To Reproduce
vapor new ComList --tempate=twostraws/vapor-clean
say yes to fluent, and leaf
select sqlite as db
cd into directory created
execute "vapor build" 
(same action with or without --template)
vapor 18.0.0
mac os 10.15.7

### Expected behavior

expect build to produce file that Xcode can cleanly open.
### Environment

vapor version does not work in 18.0.0?
* Vapor Framework version:
* Vapor Toolbox version:
* OS version:

**Comment by grundoon** [comment]
The `twostraws/vapor-clean` template is based on Vapor 3, not Vapor 4 and its completely new package architecture, so it is unsurprising that it does not play nicely with a current version of the Toolbox.

**Comment by campej** [comment]
As I mentioned, the same problem happens without the --template
Here is the build of that attempt:

Cloning template...
name: ComList
Would you like to use Fluent?
y/n> fluent: Yes
Which database would you like to use?
1: Postgres (Recommended)
2: MySQL
3: SQLite
4: Mongo
> db: SQLite
Would you like to use Leaf?
y/n> leaf: Yes
Generating project files
+ Package.swift
+ main.swift
+ configure.swift
+ routes.swift
+ Todo.swift
+ CreateTodo.swift
+ .gitkeep
+ TodoController.swift
+ AppTests.swift
+ index.leaf
+ Dockerfile
+ docker-compose.yml
+ .gitignore
+ .dockerignore
Creating git repository
Adding first commit
                                
               **               
             **~~**             
  
    ****~~~~~~~~~~++++~~****    
       *****~~~~~~~~~*****      
          *************         
                                
 _       __    ___   ___   ___  
\ \  /  / /\  | |_) / / \ | |_) 
 \_\/  /_/--\ |_|   \_\_/ |_| \ 
   a web framework for Swift    
                                
       Project ComList has been created!
                       
Use cd 'ComList' to enter the project directory
 Use vapor xcode to open the project in Xcode
Building project...
Fetching https://github.com/vapor/fluent-sqlite-driver.git
Fetching ..... https://github.com/vapor/leaf.git
Fetching https://github.com/vapor/fluent.git
Fetching https://github.com/vapor/vapor.git
Fetching https://github.com/swift-server/async-http-client.git
Fetching https://github.com/apple/swift-nio-extras.git
Fetching https://github.com/apple/swift-metrics.git
Fetching https://github.com/apple/swift-crypto.git
Fetching https://github.com/vapor/console-kit.git
Fetching https://github.com/vapor/routing-kit.git
Fetching https://github.com/apple/swift-nio-ssl.git
Fetching https://github.com/apple/swift-nio-http2.git
Fetching https://github.com/apple/swift-nio-transport-services.git
Cloning https://github.com/vapor/leaf.git
Resolving https://github.com/vapor/leaf.git at 4.0.1
Cloning https://github.com/vapor/sqlite-kit.git
Resolving https://github.com/vapor/sqlite-kit.git at 4.0.2
Cloning https://github.com/vapor/sqlite-nio.git
Resolving https://github.com/vapor/sqlite-nio.git at 1.1.0
Cloning ...... https://github.com/swift-server/async-http-client.git
Resolving https://github.com/swift-server/async-http-client.git at 1.2.2
[1/854] Compiling CoreMetrics Metrics.swift
[2/854] Compiling COperatingSystem Exports.swift
[4/855] Merging module COperatingSystem
[5/855] Compiling CURLParser urlparser.c
[1421/1429] Compiling Vapor HTTPMediaType.swift
[1422/1429] Compiling Vapor HTTPMediaTypePreference.swift
[1423/1429] Compiling Vapor Responder.swift
[1424/1429] Compiling Vapor Application+HTTP+Server.swift
[1425/1429] Compiling Vapor HTTPServer.swift
[1426/1429] Compiling Vapor HTTPServerHandler.swift
[1427/1429] Compiling Vapor HTTPServerRequestDecoder.swift
[1428/1429] Compiling Vapor HTTPServerResponseEncoder.swift
[1429/1430] Merging module Vapor
[1430/1435] Compiling App configure.swift
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/Controllers/TodoController.swift:1:8: error: could not build Objective-C module 'Fluent'
import Fluent
       ^
[1431/1435] Compiling App routes.swift
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/Controllers/TodoController.swift:1:8: error: could not build Objective-C module 'Fluent'
import Fluent
       ^
[1432/1435] Compiling App TodoController.swift
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/Controllers/TodoController.swift:1:8: error: could not build Objective-C module 'Fluent'
import Fluent
       ^
[1433/1435] Compiling App CreateTodo.swift
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/Controllers/TodoController.swift:1:8: error: could not build Objective-C module 'Fluent'
import Fluent
       ^
[1434/1435] Compiling App Todo.swift
/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/module.modulemap:2:12: error: header '/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h' not found
    header "/Users/erick/Documents/AppAfldr/ComList/.build/x86_64-apple-macosx/debug/Fluent.build/Fluent-Swift.h"
           ^
/Users/erick/Documents/AppAfldr/ComList/Sources/App/Controllers/TodoController.swift:1:8: error: could not build Objective-C module 'Fluent'
import Fluent
       ^
Fatal error: result 1: file VaporToolbox/exec.swift, line 55

**Comment by 0xTim** [comment]
@campej you probably need to update the toolbox. It's now part of Homebrew core so run:
```bash
brew uninstall vapor && brew untap vapor/tap && brew install vapor
```

**Comment by campej** [comment]
Thank you OxTim, that did clean up the missing 'Debug" problems.  Question, I did do a brew update, brew upgrade vapor, brew cleanup and brew doctor before submitting my problem.  Why would brew upgrade not upgrade the toolbox?  Does this mean that I should always untap a product and reinstall from scratch?

However, even with the clean install, up building and running in Xcode, I get the following error: 
{"error":true,"reason":"LeafError(file: \"\/Users\/erick\/XcodeDev\/ComList-aqahcgkfmexqqbeqimfbvdheztun\/SourcePackages\/checkouts\/leaf-kit\/Sources\/LeafKit\/LeafSource\/LeafSources.swift\", function: \"searchSources(t:on:s:)\", line: 73, column: 69, reason: LeafKit.LeafError.Reason.noTemplateExists(\"index\"))"}
leaf 4.0.1 and leaf-kit 1.0.0 show up in Swift Package Dependencies and Resources/View/index.leaf does exist.

**Comment by 0xTim** [comment]
The reason is because the toolbox used to be installed from the Vapor tap - the last version exposed to that was 18.0, so there were no updates. You only needed to remove the tap so you could get Vapor from Homebrew core. You shouldn't need to do that again.

For the error, you need to set your working directory, as described here https://www.timc.dev/posts/custom-working-directory/

**Comment by campej** [comment]
Thank you Tim for you fast and accurate responses.

**Comment by nguyenminhtienhust** [comment]
framework: 4.48.2
toolbox: 18.3.3

All things are upgrade, but this issues still happen when debug with Xcode, but it work when run cmd: swift run

**Comment by 0xTim** [comment]
@nguyenminhtienhust What are the actual errors you're getting? And is this M1 or Intel?

**Comment by nguyenminhtienhust** [comment]
> @nguyenminhtienhust What are the actual errors you're getting? And is this M1 or Intel?
my Old Mac using Intel
{
"error": true,
"reason": "LeafError(file: \"/Users/minhtien/Library/Developer/Xcode/DerivedData/shopnoithat-dtfmislujxsmqyerehrvpthmqrcu/SourcePackages/checkouts/leaf-kit/Sources/LeafKit/LeafSource/LeafSources.swift\", function: \"searchSources(t:on:s:)\", line: 73, column: 69, reason: LeafKit.LeafError.Reason.noTemplateExists(\"index\"))"
}


![Screen Shot 2021-07-30 at 21 12 11](https://user-images.githubusercontent.com/6380277/127665851-ff973be7-8a86-45f9-a8ba-40f184786f5a.png)

**Comment by nguyenminhtienhust** [comment]
And in my xcode:
[ WARNING ] No custom working directory set for this scheme, using /Users/minhtien/Library/Developer/Xcode/DerivedData/shopnoithat-dtfmislujxsmqyerehrvpthmqrcu/Build/Products/Debug
[ NOTICE ] Server starting on http://127.0.0.1:9090
[ INFO ] GET / [request-id: 947FC307-D12A-41ED-9FB6-D346540F34FF]
[ WARNING ] LeafError(file: "/Users/minhtien/Library/Developer/Xcode/DerivedData/shopnoithat-dtfmislujxsmqyerehrvpthmqrcu/SourcePackages/checkouts/leaf-kit/Sources/LeafKit/LeafSource/LeafSources.swift", function: "searchSources(t:on:s:)", line: 73, column: 69, reason: LeafKit.LeafError.Reason.noTemplateExists("index")) [request-id: 947FC307-D12A-41ED-9FB6-D346540F34FF]

![Screen Shot 2021-07-30 at 21 14 18](https://user-images.githubusercontent.com/6380277/127666133-c5d655fb-8b8f-4906-ba7b-4f78af190d4c.png)

**Comment by 0xTim** [comment]
Like the warning in Xcode says you haven't set a custom working directory. See the docs for more details https://docs.vapor.codes/4.0/xcode/#custom-working-directory

**Comment by nguyenminhtienhust** [comment]
> Like the warning in Xcode says you haven't set a custom working directory. See the docs for more details https://docs.vapor.codes/4.0/xcode/#custom-working-directory

OH. thanks you so much. it work now.

**Comment by dechhay** [comment]
> Like the warning in Xcode says you haven't set a custom working directory. See the docs for more details https://docs.vapor.codes/4.0/xcode/#custom-working-directory

Does this solution work when collaborating with teammates?  I see that it uses an absolute path, which uses my machine's username.

**Comment by 0xTim** [comment]
Each person needs to set the custom working directory the first time they open the project. The file that stores this information (in `.swiftpm`) should not be checked into source control
