### ISSUE TITLE
OpenSSL errors with Vapor 3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by hamchapman** [vapor/vapor#1523]
Getting this output when I try to build a Vapor 3 app on Ubuntu 16.04:

```
root@docker-testing:~/jottly/jottly-api# swift build -c release 
...
Compile Swift Module 'OpenSSL' (5 sources)
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "shim.h"
         ^
/root/jottly/jottly-api/.build/checkouts/copenssl.git--7913496663950807733/shim.h:4:10: error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^
/root/jottly/jottly-api/.build/checkouts/tls.git--7614001587941192/Sources/OpenSSL/OpenSSLClient.swift:2:8: error: could not build C module 'COpenSSL'
import COpenSSL
       ^
error: terminated(1): /root/jottly/jottly-api/swift-4.1-DEVELOPMENT-SNAPSHOT-2018-02-26-a-ubuntu16.04/usr/bin/swift-build-tool -f /root/jottly/jottly-api/.build/release.yaml main output:
```

Note that this works on macOS 10.13 just fine.

### Steps to reproduce

* Clone https://github.com/hamchapman/jottly and `cd jottly-api`
* Run `swift package update`, which will succeed
* Run `swift build -c release` and see the error output listed at the top of the issue

### Expected behavior

It should build successfully.

### Actual behavior

It does not build successfully.

### Environment

* Vapor Framework version: 3.0.0-rc.1.1
* Vapor Toolbox version: n/a
* OS version: Ubuntu 16.04

* Swift 4.1 (Feb 26th snapshot from 4.1 branch)
* `libssl-dev`: 1.0.2g-1ubuntu4.10
* `openssl`: 1.0.2g-1ubuntu4.10
* `Package.swift`: 

```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "jottly-api",
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0-rc"),

        // 🔵 Swift ORM (queries, models, relations, etc) built on SQLite 3.
        .package(url: "https://github.com/vapor/fluent-sqlite.git", from: "3.0.0-rc"),
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentSQLite", "Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"]),
    ]
)
```

* `Package.resolved`: 

```swift
{
  "object": {
    "pins": [
      {
        "package": "Async",
        "repositoryURL": "https://github.com/vapor/async.git",
        "state": {
          "branch": null,
          "revision": "887ddb41af15a39c3e47b9e0b207aa8efd8bafc3",
          "version": "1.0.0-rc.1"
        }
      },
      {
        "package": "Console",
        "repositoryURL": "https://github.com/vapor/console.git",
        "state": {
          "branch": null,
          "revision": "26812edd1d4af8129d194ee25483159b92fed4d5",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "Core",
        "repositoryURL": "https://github.com/vapor/core.git",
        "state": {
          "branch": null,
          "revision": "086a41eeeb2c97e53002950ae3b65b365759b66b",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "Crypto",
        "repositoryURL": "https://github.com/vapor/crypto.git",
        "state": {
          "branch": null,
          "revision": "9a708a33ec21f5d1eea858c10cf7e9b8306a0b30",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "DatabaseKit",
        "repositoryURL": "https://github.com/vapor/database-kit.git",
        "state": {
          "branch": null,
          "revision": "5f247a63f392d260cc7c8e9b916131a67f73dbe4",
          "version": "1.0.0-rc.1"
        }
      },
      {
        "package": "Engine",
        "repositoryURL": "https://github.com/vapor/engine.git",
        "state": {
          "branch": null,
          "revision": "cfe3ffc04b0316564a40ad8e5dfb9a355d936c25",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "Fluent",
        "repositoryURL": "https://github.com/vapor/fluent.git",
        "state": {
          "branch": null,
          "revision": "d584c55eadbfe14cda60ccf74e6f5a81401f71ee",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "FluentSQLite",
        "repositoryURL": "https://github.com/vapor/fluent-sqlite.git",
        "state": {
          "branch": null,
          "revision": "a2d70d95b660631d591a7aa1ed1a65c91f67acf3",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "Routing",
        "repositoryURL": "https://github.com/vapor/routing.git",
        "state": {
          "branch": null,
          "revision": "8210d28691a11d0d27b7a0b32117d7fd81099916",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "Service",
        "repositoryURL": "https://github.com/vapor/service.git",
        "state": {
          "branch": null,
          "revision": "90426d62cf1b028c0eef8285cb0293b527e45393",
          "version": "1.0.0-rc.1"
        }
      },
      {
        "package": "Sockets",
        "repositoryURL": "https://github.com/vapor/sockets.git",
        "state": {
          "branch": null,
          "revision": "738f3ebf3ebb8ea886d5dd8588dd46a54f66af1c",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "SQLite",
        "repositoryURL": "https://github.com/vapor/sqlite.git",
        "state": {
          "branch": null,
          "revision": "951e4f128d15a8a49e009fcf7a49f8e66e189eb7",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "TemplateKit",
        "repositoryURL": "https://github.com/vapor/template-kit.git",
        "state": {
          "branch": null,
          "revision": "cda3174c5e029526a5b11b19fcfd83bd65b6876a",
          "version": "1.0.0-rc.1.1"
        }
      },
      {
        "package": "TLS",
        "repositoryURL": "https://github.com/vapor/tls.git",
        "state": {
          "branch": null,
          "revision": "648e653758ad29f7087c95a91bc0d183712b94ab",
          "version": "3.0.0-rc.1"
        }
      },
      {
        "package": "Validation",
        "repositoryURL": "https://github.com/vapor/validation.git",
        "state": {
          "branch": null,
          "revision": "683af11976a732584baf339483aa3206734c913b",
          "version": "2.0.0-rc.1"
        }
      },
      {
        "package": "Vapor",
        "repositoryURL": "https://github.com/vapor/vapor.git",
        "state": {
          "branch": null,
          "revision": "d8254ba464b211ca6d465703f7f5d37eb0c95b65",
          "version": "3.0.0-rc.1.1"
        }
      }
    ]
  },
  "version": 1
}
```

**Comment by tanner0101** [comment]
Can you double check `libssl-dev` was correctly installed? 100% of the times I've encountered that error personally have been when I forgot to install `libssl-dev`.

**Comment by tanner0101** [comment]
Just to be sure, here's the commands we use to build Vapor on a fresh docker install for CI: https://github.com/vapor/vapor/blob/master/circle.yml#L11-L20

**Comment by hamchapman** [comment]
I've managed to get it working and have a theory for why it wasn't working, but it's just a very vague hunch.

I realise I wasn't clear with the initial report that I was trying to get it working both "directly" (ssh-ing into an Ubuntu box and trying to compile everything there) as well as with a Dockerfile, which looked like this:

```bash
FROM norionomura/swift:swift-4.1-branch

RUN apt-get -qq update
RUN apt-get install -yq libssl-dev

WORKDIR /app

COPY ./Public Public/
COPY ./Package.swift Package.swift
COPY ./Package.resolved Package.resolved
COPY ./Tests Tests/
COPY ./Sources Sources/
COPY ./.build .build/

RUN swift build -c release

EXPOSE 8080

ENV PATH /app/.build/release:$PATH

ENTRYPOINT [".build/release/Run"]
CMD ["--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
```

Neither was working, but I managed to get the "direct" (non-Docker) version working by installing `libssl-dev` again (I swear it worked yesterday, but clearly not). 

However, the Docker-version still wasn't working until I removed the `COPY ./.build .build/` step, and added a `swift package update` step before the `swift build -c release` step.

As soon as I did that, it started to work.

So my theory is that whatever ends up in `.build/` when I run `swift package update` locally (on my Mac) isn't suitable for the Ubuntu version.

So perhaps the OpenSSL stuff that gets built on a Mac is not appropriate for a Linux build, which is why they worked in isolation, but not when trying to share build artefacts between Docker runs on different OSes.

What do you think? 

Thanks for the help!

**Comment by 0xTim** [comment]
@hamchapman ah yeah if you're building from the command line locally on macOS and then try to use those things on Linux you're going to have a bad time. Never copy your `.build` directory

**Comment by hamchapman** [comment]
Yeah, makes sense. Annoyed I didn't think of it sooner!

Does `swift build` run `swift package update` if it determines it not to have already been run yet? Asking because of the lack of `swift package update` in the CircleCI example that @tanner0101 linked to above.

**Comment by 0xTim** [comment]
@hamchapman if there is no `.build` directory (as in the case of the CI builds as they're from fresh), I think it actually runs `swift package resolve` which determines what the `.resolved` file should look like and then the build function pulls the dependencies down...or something like that. `swift package update` is for updating existing dependencies with the latest versions allowed from the manifest

**Comment by hamchapman** [comment]
Ah okay, awesome. Thanks for the explanation! 

I'll close this now as it's all working now 👍
