### PR TITLE
Reducing minimum target for Concurrency related code

### PR DESCRIPTION
**Pull request by rkreutz**
Since Xcode 13.2, Swift Concurrency support has been extended to macOS 10.15, iOS 13, tvOS 13 and watchOS 6 therefore we can safely lower minimum target version on Concurrency related code

### CODE REVIEW

**Comment by 0xTim** [comment]
Unfortunately it's not a simple as this. Whilst it works for most people,  anyone on older OSes with a new Xcode won't be able to compile and this doesn't work with Xcode 13.0 and 13.1. To fix this we'd need to duplicate all the concurrency API for old Xcode and new Xcode (see [NIO as an example](https://github.com/apple/swift-nio/blob/main/Sources/NIOCore/AsyncAwaitSupport+OldXcodes.swift). The maintenance burden is too great for us to commit to (and test and keep up to date etc).

We do have plans to solve this by dropping Swift 5.4 and 5.5 with the next chunk of async work - see https://blog.vapor.codes/posts/async-next-steps/

**Comment by 0xTim** [comment]
Unfortunately that would be a breaking change, which we can't do. If someone has 5.5.0 either via Xcode or in Docker and run an update they'd get compilation errors, which we can't do I'm afraid. The best workaround is probably VSCode and remote dev containers

**Comment by rkreutz** [comment]
I'll just run my code on my forks, but hopefully this will get sorted eventually, thanks anyway
