### ISSUE TITLE
duplicate symbol __TMRbBp on build Vapor 1.2

### ISSUE THREAD

**Issue by makoni** [vapor/vapor#732]
After updating to Vapor to 1.2 it compiles with error and binary doesn't execute

At the end of build an error appears:

swift build -c release
...
/usr/bin/ld.gold: error: /home/webserver/vapor/.build/release/Vapor.build/Serve/Droplet+BootServers.swift.o: multiple definition of '_TMRbBp'
/usr/bin/ld.gold: /home/webserver/vapor/.build/release/Fluent.build/SQL/GeneralSQLSerializer.swift.o: previous definition here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/webserver/swift/usr/bin/swift-build-tool -f /home/webserver/vapor/.build/release.yaml

**Comment by petrpavlik** [comment]
Same here when I try to compile Vapor 1.2 using Swift 3.0.1 on Heroku

```
remote: Compile Swift Module 'Vapor' (86 sources)        
remote: Compile Swift Module 'App' (7 sources)        
remote: Linking ./.build/release/App        
remote: /usr/bin/ld.gold: error: /tmp/build_76ea0982ac08948442958b7f9ef9e0bb/.build/release/Vapor.build/Serve/Droplet+BootServers.swift.o: multiple definition of '_TMRbBp'        
remote: /usr/bin/ld.gold: /tmp/build_76ea0982ac08948442958b7f9ef9e0bb/.build/release/Fluent.build/SQL/GeneralSQLSerializer.swift.o: previous definition here        
remote: clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)        
remote: <unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)        
remote: <unknown>:0: error: build had 1 command failures        
remote: swift-build: error: exit(1): /app/.swiftenv/versions/3.0.1/usr/bin/swift-build-tool -f /tmp/build_76ea0982ac08948442958b7f9ef9e0bb/.build/release.yaml        
remote: Fetching Dependencies[32m [Done][0m        
remote: Building Project...        
remote: [31mError: [0mexecute(1)        
remote:  !     Push rejected, failed to compile Swift app.        
remote: 
remote:  !     Push failed        
remote: Verifying deploy....
remote: 
remote: !	Push rejected to packagecatalog.        
remote: 
To https://git.heroku.com/packagecatalog.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/packagecatalog.git'

```

**Comment by andreasley** [comment]
This is probably related to https://bugs.swift.org/browse/SR-3081
