### ISSUE TITLE
Vapor 2 doesn't compile on Xcode 9.3 when gathering code coverage data

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/vapor#1624]
Vapor 2 doesn't compile on Xcode 9.3 when gathering code coverage data.

### Steps to reproduce

- Download Vapor 2.4.4
- `swift package generate-xcodeproj`
- Edit the Vapor-Package scheme -> Test -> Tick Gather coverage for (doesn’t matter for all or some targets)
- build; it will build ok, then fail when linking

### Expected behavior

Vapor 2 should compile fine using Xcode 9.3 with Code Coverage enabled.

### Actual behavior

Vapor 2 does not compile, failing at the linker stage:

```
Undefined symbols for architecture x86_64:
  "static (extension in Foundation):Swift.String._unconditionallyBridgeFromObjectiveC(__ObjC.NSString?) -> Swift.String", referenced from:
      __C.StringTransform.rawValue.getter : Swift.String in Address+C.o
      __C.StringTransform.rawValue.getter : Swift.String in Address.o
      __C.StringTransform.rawValue.getter : Swift.String in Conversions.o
      __C.StringTransform.rawValue.getter : Swift.String in Error.o
      __C.StringTransform.rawValue.getter : Swift.String in Types.o
      __C.StringTransform.rawValue.getter : Swift.String in Descriptor.o
      __C.StringTransform.rawValue.getter : Swift.String in TCPInternetSocket.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This happens because some Vapor dependencies don’t `import Foundation`, but use `String`s.

I don’t see why that would be needed, but apparently something has changed in the way Xcode 9.3 generates the code coverage and without being able to link `Foundation` to those packages the linker fails.

Monkey patching `Sockets` adding `import Foundation`, moves the issue to the `FormData` target, and so on.

Unfortunately, linking the `Sockets` target to `Foundation` in the project file, doesn’t solve the problem.

### Environment

* Vapor Framework version: 2.4.4
* Vapor Toolbox version: 3.1.2 or 3.1.6, it doesn't matter
* OS version: 10.13.4

**Comment by 0xTim** [comment]
@valeriomazzeo I've closed this as I think the PRs required are merged now. If not, reopen
